spring:
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    cache-names: redisCache
server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    ip-address: true