swagger2:
  enable: true
server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    ip-address: true
spring:
  application:
    name: demo